-- Merchandise orders: the half of the shop that has never existed.
--
-- Today a parent could pay and nothing would be written down anywhere. These four tables record
-- what was bought, in what size, with what printed on it, for which dancer, and how far along it
-- is. Nothing here touches the class booking tables.
--
-- The shape that matters: FULFILMENT STATE LIVES ON THE LINE, NOT THE ORDER. One order can hold a
-- hoodie for Evie (Tuesday) and a tee for Jack (Saturday); an order-level "collected" cannot
-- express that, and the register flag is per dancer. The order carries a trigger-maintained
-- rollup purely so the admin console has something to sort by.

-- ---------------------------------------------------------------- print runs

create table if not exists public.merch_print_runs (
  id uuid primary key default gen_random_uuid(),
  run_number bigint generated by default as identity,
  sent_to text not null,
  sent_cc text,
  item_count integer not null default 0,
  garment_count integer not null default 0,
  status text not null default 'sent' check (status in ('sent', 'failed', 'cancelled')),
  -- So "did he actually get that batch?" has an answer.
  email_log_id uuid,
  -- Exactly what was emailed, frozen. Products get renamed and prices change.
  summary jsonb,
  created_by uuid,
  created_at timestamp with time zone not null default now()
);

-- ---------------------------------------------------------------- orders

create table if not exists public.merch_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  -- Plain uuid, not a FK: this schema never references auth.users directly.
  parent_id uuid not null,
  -- Snapshots. A family changing their email later must not rewrite old receipts.
  contact_email text,
  contact_name text,
  subtotal_pence integer not null default 0,
  total_pence integer not null default 0,
  stripe_env text,
  stripe_payment_intent_id text,
  application_fee_pence integer,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'sent_to_print', 'ready', 'collected',
                      'expired', 'cancelled', 'refunded')),
  paid_at timestamp with time zone,
  -- Idempotency stamps. The webhook and the polling fallback both run by design, so every
  -- side effect has to be able to say "already done".
  stock_applied_at timestamp with time zone,
  confirmation_email_sent_at timestamp with time zone,
  summarised_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- One order per payment intent, so a replayed webhook cannot create a second.
create unique index if not exists merch_orders_payment_intent_key
  on public.merch_orders (stripe_payment_intent_id)
  where stripe_payment_intent_id is not null;

create index if not exists merch_orders_parent_idx on public.merch_orders (parent_id, created_at desc);
create index if not exists merch_orders_status_idx on public.merch_orders (status);
-- The daily digest reads this.
create index if not exists merch_orders_paid_at_idx on public.merch_orders (paid_at) where paid_at is not null;

-- ---------------------------------------------------------------- lines

create table if not exists public.merch_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.merch_orders(id) on delete cascade,

  -- set null, not cascade: deleting a product must not erase the history of it being sold.
  item_id uuid references public.merchandise_items(id) on delete set null,
  variant_id uuid references public.merchandise_variants(id) on delete set null,

  -- Snapshots, for the same reason.
  product_name text not null,
  size text,
  category text,
  sku text,

  -- Who it is for. student_id is nullable on purpose: an adult with no dancer profile can buy
  -- for themselves, and then there is no dancer and nothing to show on a register.
  student_id uuid references public.students(id) on delete set null,
  attendee_name text,

  quantity integer not null default 1 check (quantity between 1 and 20),
  unit_price_pence integer not null default 0,
  line_total_pence integer not null default 0,

  -- Bundles: every garment is still its own row so it gets its own size, print line and
  -- fulfilment state. bundle_ref ties the components of one bundle purchase together.
  bundle_id uuid references public.merchandise_bundles(id) on delete set null,
  bundle_ref uuid,

  status text not null default 'pending'
    check (status in ('pending', 'paid', 'sent_to_print', 'ready', 'collected',
                      'expired', 'cancelled', 'refunded')),
  print_run_id uuid references public.merch_print_runs(id) on delete set null,
  sent_to_print_at timestamp with time zone,
  ready_at timestamp with time zone,
  collected_at timestamp with time zone,
  collected_by uuid,
  collected_session_id uuid,
  created_at timestamp with time zone not null default now()
);

-- The two hot paths.
create index if not exists merch_order_items_ready_for_student_idx
  on public.merch_order_items (student_id) where status = 'ready';
create index if not exists merch_order_items_print_queue_idx
  on public.merch_order_items (print_run_id) where status = 'paid';
create index if not exists merch_order_items_order_idx on public.merch_order_items (order_id);

-- ---------------------------------------------------------------- personalisation on a line

create table if not exists public.merch_order_item_personalisations (
  id uuid primary key default gen_random_uuid(),
  order_item_id uuid not null references public.merch_order_items(id) on delete cascade,
  placement text not null check (placement in ('front', 'back', 'sleeve')),
  text text not null,
  -- Snapshot: changing the price later must never re-price a placed order.
  price_each_pence integer not null default 0,
  created_at timestamp with time zone not null default now(),
  unique (order_item_id, placement)
);

create index if not exists merch_order_item_personalisations_item_idx
  on public.merch_order_item_personalisations (order_item_id);

-- ---------------------------------------------------------------- rollup

-- The order's status is the least-advanced of its live lines, so "what still needs doing?" is
-- answerable without a join. Cancelled and refunded lines are ignored unless that is all there is.
create or replace function public.merch_order_rollup_status(_order_id uuid)
returns text
language sql
stable
set search_path = public
as $$
  with ranked as (
    select status,
           case status
             when 'pending' then 0
             when 'paid' then 1
             when 'sent_to_print' then 2
             when 'ready' then 3
             when 'collected' then 4
             else 9
           end as rank
    from public.merch_order_items
    where order_id = _order_id
  )
  select coalesce(
    (select status from ranked where rank < 9 order by rank limit 1),
    (select status from ranked order by rank limit 1),
    'pending'
  );
$$;

create or replace function public.merch_orders_sync_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _order_id uuid := coalesce(new.order_id, old.order_id);
begin
  update public.merch_orders
     set status = public.merch_order_rollup_status(_order_id),
         updated_at = now()
   where id = _order_id;
  return null;
end;
$$;

drop trigger if exists merch_order_items_rollup on public.merch_order_items;
create trigger merch_order_items_rollup
  after insert or update of status or delete on public.merch_order_items
  for each row execute function public.merch_orders_sync_status();

-- ---------------------------------------------------------------- RLS

alter table public.merch_print_runs enable row level security;
alter table public.merch_orders enable row level security;
alter table public.merch_order_items enable row level security;
alter table public.merch_order_item_personalisations enable row level security;

-- Families read their own orders and nothing else. Every WRITE is service-role or admin --
-- matching bookings_no_direct_parent_insert, so a parent cannot invent a paid order.
drop policy if exists "Parents can view own merch orders" on public.merch_orders;
create policy "Parents can view own merch orders"
  on public.merch_orders for select to authenticated
  using (auth.uid() = parent_id or public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admins manage merch orders" on public.merch_orders;
create policy "Admins manage merch orders"
  on public.merch_orders for all to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Parents can view own merch order items" on public.merch_order_items;
create policy "Parents can view own merch order items"
  on public.merch_order_items for select to authenticated
  using (
    public.has_role(auth.uid(), 'admin')
    or exists (
      select 1 from public.merch_orders o
      where o.id = merch_order_items.order_id and o.parent_id = auth.uid()
    )
  );

drop policy if exists "Admins manage merch order items" on public.merch_order_items;
create policy "Admins manage merch order items"
  on public.merch_order_items for all to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Parents can view own merch personalisation" on public.merch_order_item_personalisations;
create policy "Parents can view own merch personalisation"
  on public.merch_order_item_personalisations for select to authenticated
  using (
    public.has_role(auth.uid(), 'admin')
    or exists (
      select 1
      from public.merch_order_items i
      join public.merch_orders o on o.id = i.order_id
      where i.id = merch_order_item_personalisations.order_item_id and o.parent_id = auth.uid()
    )
  );

drop policy if exists "Admins manage merch personalisation" on public.merch_order_item_personalisations;
create policy "Admins manage merch personalisation"
  on public.merch_order_item_personalisations for all to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

-- Print runs are Amie's business only. Staff get no policy on any of these tables at all --
-- coaches see exactly what the collection RPCs return and nothing more.
drop policy if exists "Admins manage merch print runs" on public.merch_print_runs;
create policy "Admins manage merch print runs"
  on public.merch_print_runs for all to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

-- ---------------------------------------------------------------- settings

insert into public.app_settings (key, value, description)
values
  ('merch_print_email', '', 'Where print runs are emailed. The printing company''s business address.'),
  ('merch_print_cc', '', 'Optional CC on print run emails.'),
  ('merch_summary_watermark', '', 'Timestamp of the last merchandise daily summary. Everything paid since then goes in the next one.')
on conflict (key) do nothing;
